theme = "monokai_pro"

[editor]
auto-save = true
color-modes = true
true-color = true
rulers = [80, 110]

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
]
center = [
]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "primary-selection-length",
  "selections",
  "position-percentage",
  "total-line-numbers",
  # "file-encoding",
  # "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
display-messages = true

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
"C-w" = { "C-c" = "wclose", c = "wclose" }
g = { a = "code_action" }

# ";" = ":write" # Not ":"

C-y = "scroll_up"
C-e = "scroll_down"
G = "goto_last_line"
