theme = "monokai_pro"

[editor]
auto-save = true
color-modes = true
true-color = true
rulers = [80, 110]
completion-replace = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-modification-indicator",
]
center = [
  # "file-base-name",
  "version-control",
]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "primary-selection-length",
  "selections",
  # "position",
  "position-percentage",
  "total-line-numbers",
  # "file-encoding",
  # "file-line-ending",
  "file-type",
]
separator = "│"

[editor.lsp]
display-messages = true
auto-signature-help = false # this is covering completions
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.search]
wrap-around = false

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

# from reddit
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
x = "extend_line"
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
C-space = "signature_help"

# vim goodness
G = "goto_last_line"
# "^" = "goto_first_nonwhitespace"
# "$" = "goto_line_end"
C-w = { C-c = "wclose", c = "wclose" }
C-r = "redo"
C-y = "scroll_up"
C-e = "scroll_down"
# D = ["extend_to_line_end", "delete_selection"]

# attempt at removing wayward white space
Y = [
  "save_selection",
  "select_all",
  # Delete trailing whitespace from end of each line
  ":pipe sed 's/[ \t]*$//'",
  # Delete trailing blank lines (including whitespace) from end of the buffer
  ":pipe awk '/^\\s*$/ {b=b $0 \"\\n\"; next;} {printf \"%s\",b; b=\"\"; print;}'",
  "collapse_selection",
  "jump_backward",
  "commit_undo_checkpoint",
  ":write",
]

[keys.normal.";"]
w = ":write"
";" = ":w"
a = "code_action"

[keys.normal.g]
a = "code_action"

[keys.normal."space"]
G = ":run-shell-command lazygit; pkill -WINCH hx" # Open LazyGit

[keys.normal.Z]
Z = ":write-quit-all"

[keys.select]
x = "extend_line"
";" = ["collapse_selection", "normal_mode"]
V = "extend_to_line_end"

[keys.insert]
C-q = "collapse_selection"
C-space = "signature_help"
