theme = "monokai_pro"

[editor]
auto-save = true
color-modes = true
true-color = true
rulers = [80, 110]
completion-replace = true

cursorline = true
cursorcolumn = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = [
  # "file-base-name",
  "version-control",
]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "primary-selection-length",
  "selections",
  # "position",
  "position-percentage",
  "total-line-numbers",
  # "file-encoding",
  # "file-line-ending",
  "file-type",
]
separator = "│"

[editor.lsp]
display-messages = true
auto-signature-help = true # this is covering completions
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.search]
wrap-around = false

[editor.whitespace]
# render = "all"

[editor.indent-guides]
render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# character = "▏"
# character = "|"
# character = "┊"
# character = "⸽"
# character = "┇"
# character = "┆"
character = "┋"
# character = "╏"
skip-levels = 1

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

# from reddit
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
# D = ["ensure_selections_forward", "extend_to_line_end"]
D = ["goto_first_nonwhitespace", "extend_line", "delete_selection"]
x = "extend_line"
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
C-space = "signature_help"
c = ["trim_selections", "change_selection"]

# vim goodness
G = "goto_last_line"
# "^" = "goto_first_nonwhitespace"
# "$" = "goto_line_end"
C-w = { C-c = "wclose", c = "wclose" }
C-r = "redo"
C-y = "scroll_up"
C-e = "scroll_down"

[keys.normal.";"]
w = ":write"
";" = ":w"
a = "code_action"
o = [":hsplit ~/.config/helix/config.toml"]
r = [":config-reload"]
# remove wayward white space
space = [
  "save_selection",
  "select_all",
  ":pipe trim-whitespace",
  "collapse_selection",
  "jump_backward",
  "commit_undo_checkpoint",
  ":write",
]
c = [":character-info"]
t = ":run-shell-command make test"

[keys.normal.g]
a = "code_action"

[keys.normal."space"]
B = "file_picker_in_current_buffer_directory"

[keys.normal.Z]
Z = ":write-quit-all"
Q = ":quit-all"

[keys.select]
x = "extend_line"
";" = ["collapse_selection", "normal_mode"]
V = "extend_to_line_end"

[keys.insert]
C-q = "collapse_selection"
C-space = "signature_help"
