[[language]]
name = "hcl"
scope = "source.tf"
roots = ["main.tf", ".terraform.d"]
file-types = ["hcl", "tf"]
auto-format = true
formatter = { command = "/home/jcmuller/.asdf/shims/terraform", args = ["fmt", "-"] }
language-server = { command = "terraform-lsp" }
#language-server = { command = "terraform-ls", args = ["-"] } 
[[language]]
name = "go"
formatter = { command = "goimports" }
