#!/usr/bin/perl

use strict;
use FileHandle;

my $file;
{
	my $n = `mktemp -p /tmp/ mutt_XXXXXXXXXX`;
	$n =~ s/\n//g;
	system(qq|mv "$n" "$n.html"|);
	$file = "$n.html";
}

{
	my $fh = new FileHandle("> $file");

	if (defined $fh)
	{
		print $fh join('', <>);
	}
	$fh->close();
}

#system('google-chrome', $file);
system('firefox', $file);

