---
version: 2

commands:
  - command: nvim
    arguments:
      - ${INPUT}
    title: Edit in Nvim

tools:
  eruby-erb: &eruby-erb
    lint-command: "erb -x -T - | ruby -c"
    lint-stdin: true
    lint-offset: 1
    format-command: htmlbeautifier

  vim-vint: &vim-vint
    lint-command: "vint -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  make-checkmake: &make-checkmake
    lint-command: "checkmake"
    lint-stdin: true

  markdown-markdownlint: &markdown-markdownlint
    lint-command: markdownlint --stdin
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

  markdown-pandoc: &markdown-pandoc
    format-command: "pandoc -f markdown -t gfm -sp --tab-stop=2"

  markdown-prettier: &markdown-prettier
    format-command: "/home/jcmuller/.asdf/shims/prettier --parser markdown"

  rst-pandoc: &rst-pandoc
    format-command: "pandoc -f rst -t rst -s --columns=79"

  rst-lint: &rst-lint
    lint-command: "rst-lint"
    lint-formats:
      - "%tNFO %f:%l %m"
      - "%tARNING %f:%l %m"
      - "%tRROR %f:%l %m"
      - "%tEVERE %f:%l %m"

  yaml-yamllint: &yaml-yamllint
    lint-command: "yamllint -f parsable -"
    lint-stdin: true

  yaml-prettier: &yaml-prettier
    format-command: "/home/jcmuller/.asdf/shims/prettier --parser yaml"

  python-flake8: &python-flake8
    lint-command: "flake8 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  python-mypy: &python-mypy
    lint-command: "mypy --show-column-numbers"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: "hadolint"
    lint-formats:
      - "%f:%l %m"

  ruby-rubocop: &ruby-rubocop
    lint-command: bundle exec rubocop --config .rubocop.yml
    lint-formats:
      - "%f:%l:%c: %t: %m"
        #format-command:
        #  bundle exec rubocop
        #  --config .rubocop.yml
        #  --auto-correct
        #  --stderr
        #format-stdin: true

  ruby-standard: &ruby-standard
    lint-command: standardrb --no-fix
    lint-formats:
      - "%f:%l:%c: %t: %m"
    format-command: standardrb --fix
      #format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: "shellcheck -f gcc -x"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  sh-shfmt: &sh-shfmt
    # Tabs
    # format-command: "shfmt -ci -s -bn"
    # Spaces
    format-command: "shfmt -ci -s -bn -i 2"
    format-stdin: true

  javascript-eslint: &javascript-eslint
    lint-command: "eslint -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true

  html-prettier: &html-prettier
    format-command: "/home/jcmuller/.asdf/shims/prettier --parser html"

  css-prettier: &css-prettier
    format-command: "/home/jcmuller/.asdf/shims/prettier --parser css"

  json-prettier: &json-prettier
    format-command: "/home/jcmuller/.asdf/shims/prettier --parser json"

  json-jq: &json-jq
    lint-command: "jq ."

  json-fixjson: &json-fixjson
    format-command: "fixjson"

  csv-csvlint: &csv-csvlint
    lint-command: "csvlint"

  any-excitetranslate: &any-excitetranslate
    hover-command: "excitetranslate"
    hover-stdin: true

  terraform-lint: &terraform-lint
    lint-command: tflint
    lint-stdin: true

  terraform-format: &terraform-format
    format-command: terraform fmt
    format-stdin: true

languages:
  eruby:
    - <<: *eruby-erb

  vim:
    - <<: *vim-vint

  make:
    - <<: *make-checkmake

  markdown:
    - <<: *markdown-markdownlint
    - <<: *markdown-pandoc
    - <<: *markdown-prettier

  rst:
    - <<: *rst-lint
    - <<: *rst-pandoc

  yaml:
    - <<: *yaml-yamllint
    - <<: *yaml-prettier

  python:
    - <<: *python-flake8
    - <<: *python-mypy

  dockerfile:
    - <<: *dockerfile-hadolint

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  javascript:
    - <<: *javascript-eslint

  html:
    - <<: *html-prettier

  css:
    - <<: *css-prettier

  json:
    - <<: *json-jq
    - <<: *json-fixjson
    - <<: *json-prettier

  csv:
    - <<: *csv-csvlint

  terraform:
    - <<: *terraform-lint
    - <<: *terraform-format

  ruby:
    #- <<: *ruby-rubocop
    - <<: *ruby-standard

  _:
    - <<: *any-excitetranslate
