---
GITHUB_NOTIFICATIONS_USER_NAME: !var tools/github_notifications/username
GITHUB_NOTIFICATIONS_PASSWORD: !var tools/github_notifications/password

RESTRICTED_REPOSITORIES_PATTERN: .+
RESTRICTED_REPOSITORIES_ALLOWED_REASONS: (author|assign)
