#!/usr/bin/perl

use strict;
use FileHandle;

my $file;
{
    my $n = `mktemp -p /tmp/ mutt_XXXXXXXXXX`;
    $n =~ s/\n//g;
    rename "$n", "$n.html";
    $file = "$n.html";
}

{
    my $fh = new FileHandle("> $file");
    print $fh join('', <>) if (defined $fh);
    $fh->close();
}

#system('chromium', '-app', $file);
#system('firefox', $file);
#system('surf', $file);
#system('qpm', 'run', 'work', "$file");
#system('qp', '--load', 'work', "$file");
#sleep 2;
#system('qutebrowser-home', $file);
#system('qutebrowser', $file);
system('qutebrowser', $file);
sleep 5;
unlink $file;
