c.fonts.prompts = "10pt sans-serif"
c.fonts.default_size = "9px"
c.fonts.default_family = "terminus"
c.fonts.statusbar = "9px terminus"
c.fonts.tabs.selected = "9px terminus"
c.fonts.tabs.unselected = "9px terminus"
c.zoom.default = "85%"
