#set -x

# Path to your oh-my-zsh installation.
#export ZSH=/home/jcmuller/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="juancmuller"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(git docker aws tmux thor rbenv heroku hub go git-extras)
#plugins=(docker aws tmux thor heroku go rbenv git hub git-extras)

# User configuration
PASSWORD_STORE_GPG_OPTS="--armor"; export PASSWORD_STORE_GPG_OPTS
PASSWORD_STORE_GENERATED_LENGTH=36; export PASSWORD_STORE_GENERATED_LENGTH

AWS_VAULT_BACKEND=secret-service; export AWS_VAULT_BACKEND
DAJOKU_USER=juan@greenhouse.io; export DAJOKU_USER
BROWSER=/home/jcmuller/go/bin/picky; export BROWSER
NVIM_LISTEN_ADDRESS="/tmp/neovim.sock"; export NVIM_LISTEN_ADDRESS
NVM_AUTO_USE=true; export NVM_AUTO_USE
NVM_DIR="$HOME/.nvm"; export NVM_DIR
NVM_LAZY_LOAD=true; export NVM_LAZY_LOAD
PERL5LIB="/home/jcmuller/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/jcmuller/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/jcmuller/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/jcmuller/perl5"; export PERL_MM_OPT;
QT_QPA_PLATFORMTHEME=qt5ct; export QT_QPA_PLATFORMTHEME
REPORTTIME=5; export REPORTTIME
TIMEFMT="'$fg[green]%J$reset_color' time: $fg[yellow]%*Es$reset_color, cpu: $fg[yellow]%P$reset_color, mem: $fg[yellow]%M$reset_color"; export TIMEFMT

unset SSH_AGENT_PID SSH_AUTH_SOCK

PATH_COMPONENTS=(
"$HOME/bin"
"$HOME/.cargo/bin"
"$HOME/.local/bin"
"$HOME/perl5/bin"
"$HOME/.yarn/bin"
"/usr/local/sbin"
"/usr/local/bin"
"/usr/sbin"
"/usr/bin"
"/sbin"
"/bin"
"/usr/games"
"/usr/local/games"
"/usr/local/openresty/bin"
"/usr/local/openresty/nginx/sbin"
)
PATH=${(j/:/)PATH_COMPONENTS}
export PATH

# export MANPATH="/usr/local/man:$MANPATH"

# source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

source ~/.antigen-src/antigen.zsh

antigen use oh-my-zsh

antigen theme /home/jcmuller/Development/MyStuff/custom-oh-my-zsh themes/juancmuller.zsh-theme

antigen bundles <<EOBUNDLE
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-completions src
  zsh-users/zsh-autosuggestions

  aws
  docker
  docker-compose
  git
  git-extras
  go
  pass
  rbenv
  ruby
  thor
  tmux

  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh aliases.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh colors.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh directories.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh enable-edit-command-line.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh environment.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh extra.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh gh-aliases.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh git_funcs.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh go-setup.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh jenkins.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh local.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh nvim.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh plugins
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh rbenv.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh vi-mode.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh zeus.zsh
  /home/jcmuller/Development/MyStuff/custom-oh-my-zsh zsh_completions.zsh

  github/hub etc/hub.zsh_completion

  lukechilds/zsh-nvm
EOBUNDLE

# antigen bundle jcmuller/custom-oh-my-zsh aliases.zsh
# antigen bundle jcmuller/custom-oh-my-zsh colors.zsh
# antigen bundle jcmuller/custom-oh-my-zsh directories.zsh
# antigen bundle jcmuller/custom-oh-my-zsh enable-edit-command-line.zsh
# antigen bundle jcmuller/custom-oh-my-zsh environment.zsh
# antigen bundle jcmuller/custom-oh-my-zsh extra.zsh
# antigen bundle jcmuller/custom-oh-my-zsh gh-aliases.zsh
# antigen bundle jcmuller/custom-oh-my-zsh git_funcs.zsh
# antigen bundle jcmuller/custom-oh-my-zsh go.zsh
# antigen bundle jcmuller/custom-oh-my-zsh jenkins.zsh
# antigen bundle jcmuller/custom-oh-my-zsh local.zsh
# antigen bundle jcmuller/custom-oh-my-zsh nvim.zsh
# antigen bundle jcmuller/custom-oh-my-zsh plugins
# antigen bundle jcmuller/custom-oh-my-zsh rbenv.zsh
# antigen bundle jcmuller/custom-oh-my-zsh zsh_completions.zsh

antigen apply

set noclobber

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

xmodmap ~/.Xmodmap
